url: localhost:4000
baseurl:

# Site settings
title: José Godoy
email: jmartgod@gmail.com
description: "Bienvenido a mi currículum"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
# - name:
#   pic:
#   position:
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: José Godoy
  pic: 1
  position: No dudes en contactar conmigo.
  social:
    - title: twitter
      url: http://twitter.com/godenoughfor
    - title: facebook
      url: #
    - title: linkedin
      url: https://es.linkedin.com/in/jmartgod

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/godenoughfor
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/godenoughfor

# Postal address (add as many lines as necessary)
address:
  - line: Capitá Alfons Vives, 28 4Izq
  - line: Elche, ALICANTE 03201

# Build settings
markdown: kramdown
permalink: pretty
